add debug

diff --git a/.github/workflows/workflow4.yml b/.github/workflows/workflow4.yml
--- a/.github/workflows/workflow4.yml
+++ b/.github/workflows/workflow4.yml
@@ -32,6 +32,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Debug Version Output
+        run: echo "New Version: ${{ steps.semantic.outputs.new_release_published }}"
+
   # Build and Push Docker Image
   build-and-push:
     runs-on: ubuntu-latest
@@ -49,8 +52,12 @@ jobs:
       - name: Build and Push Docker Image
         env:
           IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
-          IMAGE_VERSION: ${{ needs.versioning.outputs.new_version }}
+          IMAGE_VERSION: ${{ needs.versioning.outputs.new_version || 'latest' }}
         run: |
+          if [[ -z "$IMAGE_VERSION" ]]; then
+            echo "Error: IMAGE_VERSION is empty!"
+            exit 1
+          fi
           docker build -t $IMAGE_NAME:$IMAGE_VERSION .
           docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_NAME:latest
           docker push $IMAGE_NAME:$IMAGE_VERSION
